### ISSUE TITLE
WebSocket connection to 'ws://localhost:8080/' failed

### ISSUE THREAD

**Issue by OmegaOrbitals** [hnasr/javascript_playground#71]
Running this code on the DevConsole

let ws = const ws = new WebSocket("ws://localhost:8080")

returns WebSocket connection to 'ws://localhost:8080/' failed

**Comment by rahul-dey99** [comment]
> Running this code on the DevConsole
> 
> let ws = const ws = new WebSocket("ws://localhost:8080")
> 
> returns WebSocket connection to 'ws://localhost:8080/' failed

Why are you even using that?

**Comment by OmegaOrbitals** [comment]
> > Running this code on the DevConsole
> > 
> > let ws = const ws = new WebSocket("ws://localhost:8080")
> > 
> > returns WebSocket connection to 'ws://localhost:8080/' failed
> 
> Why are you even using that?
> 

This was 1 year ago, I've figured it out.

**Comment by dr-naikare** [comment]
> > > Running this code on the DevConsole
> > > let ws = const ws = new WebSocket("ws://localhost:8080")
> > > returns WebSocket connection to 'ws://localhost:8080/' failed
> > 
> > 
> > Why are you even using that?
> 
> This was 1 year ago, I've figured it out.

hey , can you tell me how you solved that ? am facing the same issue but am using 
let webs = new WebSocket("ws://localhost:8000");
and getting the following error on the console 

Refused to connect to 'ws://localhost:8000/' because it violates the following Content Security Policy directive: "connect-src chrome://resources chrome://theme 'self'".
